version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: alertops_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: alertops_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"

  alertops-database-restorer:
    image: "bitnami/postgresql:14.1.0"
    user: root
    environment:
      PGUSER: "alertops_user"
      PGPASSWORD: "password123"
      PGHOST: "db"
      PGDATABASE: "alertops_db"
    command:
      - "sh"
      - "-c"
      - >
        psql --dbname=$PGDATABASE --username=$PGUSER --host=$PGHOST --file=/tmp/alertops-db.sql || echo "An error occurred while restoring the database" /tmp/alertops-database-restorer-healthcheck.sh
    volumes:
      - ./config/alertops-db.sql:/tmp/alertops-db.sql
      - ./config/healthcheck/alertops-database-restorer-healthcheck.sh:/tmp/alertops-database-restorer-healthcheck.sh
    depends_on:
      db:
        condition: service_healthy

  alertops-database-exporter:
    image: "bitnami/postgresql:14.1.0"
    user: "root"
    environment:
      PGUSER: "alertops_user"
      PGPASSWORD: "password123"
      PGHOST: "db"
      PGDATABASE: "alertops_db"
    command: >
      sh -c 'pg_dump --dbname=$PGDATABASE --username=$PGUSER --host=$PGHOST --file=/backup/alertops-db.sql'
    volumes:
      - ./backup:/backup
    restart: "no"
    profiles:
      - export

volumes:
  pgdata: